version: '3.8'

services:
  fleetmanagement:
    build:
      context: .
      dockerfile: Dockerfile
    image: myuser/fleetmanagement:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"
    networks:
      - default

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
    - 27018:27017
    volumes:
    - mongodb_data_container:/data/db
    networks:
      - default

volumes:
    mongodb_data_container:
    images_data:
        external: false
networks:
  default:
    driver: bridge