version: '3.8'

services:
  fleetmanagement:
    build:
      context: .
      dockerfile: Dockerfile
    image: myuser/fleetmanagement:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    networks:
      - default

networks:
  default:
    driver: bridge